
server:
  port: 7477
  contextPath: "/"
spring:
  name: JPA Demo
  main:
    show-banner: false
  jpa:
    database: MYSQL
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    platform: mysql
    url: localhost:3306?mysql
    username: root
    password: password
    testWhileIdle: true
    validationQuery: SELECT 1

logging:
  path: $HOME/logs
  file: jpademo.log
  level:
    root: DEBUG
  root:
      org:
        springframework:
          security: DEBUG