spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sakila?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
# MyBatis-plus
mybatis-plus:
  mapper-locations: classpath*:mybatisPlus/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.art2cat.dev.maindemo.*.entity,com.art2cat.dev.common.*.entity
  global-config:
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: NOT_EMPTY
      db-type: mysql
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: false
server:
  port: 1231
