DROP TABLE IF EXISTS `rabbitmq_request`;

CREATE TABLE `rabbitmq_request` (
  `RABBITMQ_ID` varchar(32) NOT NULL COMMENT '消息ID',
  `RABBITMQ_TYPE` varchar(255) DEFAULT NULL COMMENT '消息名称',
  `RABBITMQ_CONTEXT` text COMMENT '消息内容',
  `RABBITMQ_REMARK` varchar(255) DEFAULT NULL COMMENT '消息描述',
  `DEL_FLAG` tinyint(1) DEFAULT '1' COMMENT '逻辑删除标识(1正常 0删除)',
  `REMARK` varchar(500) DEFAULT NULL COMMENT '备注说明',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (`RABBITMQ_ID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='消息请求表';