# 数据源配置
spring:
    datasource:
        driver-class-Name: com.mysql.cj.jdbc.Driver
        platform: mysql
        url: jdbc:mysql://localhost:3306/dev?useUnicode=true&useJDBCCompliantTimezoneShift=true&
            useLegacyDatetimeCode=false&serverTimezone=UTC&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&
            storage_engine=InnoDB
        username: root
        password: password
